### PR TITLE
Add support large object based on file size 

### PR DESCRIPTION
**Pull request by anhphamt**
In the sample of php-opencloud, I see an example to allow create large object in segments (1GB).

https://github.com/php-opencloud/openstack/blob/master/samples/object_store/v1/objects/create_large_object.php

### CODE REVIEW

**Comment by chrisnharvey** [comment]
Thanks for this and apologies for the delay in reviewing this. Looks good to me. Could you update the tests?

**Comment by anhphamt** [comment]
OK let me update the test and re-submit again.

**Comment by dav-is** [comment]
Update on this?

**Comment by sausin** [comment]
@anhphamt The current implementation fails tests with this error

`BadMethodCallException: Method Mockery_0_OpenStack_ObjectStore_v1_Models_Container::getObject() does not exist on this mock object`

A bit of digging suggests that the implementation might be wrong. The size method is called on the object, but it cannot exist yet as the upload hasn't yet happened.

Further, the createLargeObject support seems to be limited only to streams. Refer excerpt from the openstack v1 container

```php
public function createLargeObject(array $data): Object
    {
        /** @var \Psr\Http\Message\StreamInterface $stream */
        $stream = $data['stream'];
```
I've tried to change the implementation accordingly but can't get it to work as the `getSize` method on the `Stream` results in the private `size` getting updated which still fails the tests as it is no longer recognized as a correct object.

It would be great if this could be figured out as having this feature would be really nice!

**Comment by anhphamt** [comment]
@sausin I will back to this in few days.

**Comment by sausin** [comment]
:+1:

**Pull request closed without merging**
