### PR TITLE
Provision for parameters in dependent implementation

### PR DESCRIPTION
**Pull request by sausin**
The current implementation does not allow for more parameters to be added to the object being upload (for eg, `deleteAfter`, `deleteAt` etc). See additional parameters [here](https://github.com/php-opencloud/openstack/blob/master/src/ObjectStore/v1/Params.php)

By having a method in the adapter, any dependent implementation (like [my package](https://github.com/sausin/laravel-ovh/)) can add these additional parameters, if required, by overriding the new `getData` method without having to change the base implementation of `write`, or `writeStream` methods

### CODE REVIEW

**Comment by sausin** [comment]
If this change is okay, it would be awesome if you could please add a new release so another merged PR allowing configuration of `segmentSize` would be available :smiley:

**Comment by mzur** [comment]
The original author hasn't created a new release for some time. That's why I created my [fork](https://github.com/mzur/flysystem-openstack-swift) with the most recent updates. If the author continues to be unresponsive, consider to use the fork instead.

**Comment by sausin** [comment]
@mzur Thanks for the info! I've created the pull request :+1:

**Comment by chrisnharvey** [comment]
Thank you.

I am picking this project back up now.

@mzur If you like, I can give you write access to this repository so you can help maintain the project?

**Comment by mzur** [comment]
@chrisnharvey Yes, sure. I'll merge the current [differences](https://github.com/nimbusoftltd/flysystem-openstack-swift/compare/master...mzur:master) between our repos then.

**Comment by chrisnharvey** [comment]
@mzur Awesome! I've given you access to the repo.

**Pull request merged**
